# -*- coding: utf-8 -*-
"""Sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TIeZcqthONO2iJX7pDwX861yrGmK0Z8f
"""

!pip install kaggle

import os
import json
from zipfile import ZipFile
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding , LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

with ZipFile("IMDB Dataset.csv.zip","r") as zip_ref:
  zip_ref.extractall()

!ls

data = pd.read_csv("/content/IMDB Dataset.csv")

data.shape

data.head()

data.tail()

data["sentiment"].value_counts()

data.replace({"sentiment":{"positive":1,"negative":0}},inplace=True)

data.head()

data["sentiment"].value_counts()

train_data,test_data = train_test_split(data,test_size = 0.2, random_state = 42)

print(train_data.shape)
print(test_data.shape)

tokenizer = Tokenizer(num_words = 5000)
tokenizer.fit_on_texts(train_data["review"])
X_train = pad_sequences(tokenizer.texts_to_sequences(train_data["review"]), maxlen= 200)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_data["review"]), maxlen= 200)

print(X_train)

print(X_test)

Y_train = train_data["sentiment"]
Y_test = test_data["sentiment"]

print(Y_train)

print(Y_test)

"""LSTM - Long Short Term Memory"""

model = Sequential()
model.add(Embedding(input_dim=5000,output_dim=128,input_length=200))
model.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(1,activation="sigmoid"))

model.summary()

model.build(input_shape=(None, 200))
model.summary()

model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

model.fit(X_train,Y_train,epochs=5,batch_size=64,validation_split=0.2)

loss , accuracy = model.evaluate(X_test,Y_test)
print("Test Loss:{loss}")
print("Test Accuracy:{accuracy}")

def predict_sentiment(review):
  sequence = tokenizer.texts_to_sequences([review])
  padded_sequence = pad_sequences(sequence,maxlen=200)
  prediction = model.predict(padded_sequence)
  sentiment = "positive" if prediction[0][0] > 0.5 else " negative"
  return sentiment

new_review = "This movie was fantastic. I loved it."
sentiment = predict_sentiment(new_review)
print(f"The sentiment of the review is : {sentiment}")

new_review = "I am not going to suggest you to watch that movie "
sentiment = predict_sentiment(new_review)
print(f"The sentiment of the review is : {sentiment}")

